
language: node_js
node_js:
  - "0.12"

env:
  global:
  - GH_REF: github.com/biblesoapopera/demo.git
  - secure: HhVk/y1+niW7WJlU5xBsqhYS26HpMdMvdHecuwUi4e+tdhUu4wp3PtRyJXjIlf/g4gxeUEF27KPP6WUm7z6r08lnaEFMNy9O2Mqary6OPmw1I63RqaSm8U5Y1DMqMmJTrWB4quMsTAjbrtQwhexqeIjSbahPfzWSY1ioVvXbve4=

script:
  - node gulp.js --dist
  - bash ./deploy.sh
